name: test pypi

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      SHELL: /bin/bash

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install pyhamcrest
        pip3 install commodity
        pip3 show -f commodity
        python3 -c "import commodity"
    - name: Test
      run: |
        python3 -c "from commodity.testing import assert_that; print(assert_that)"
    - name: Test
      run: |
        echo "hola"
